apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "daemonjob-controller.name" . }}
    chart: {{ template "daemonjob-controller.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "daemonjob-controller.fullname" . }}-script
data:
  sync.py: |-
    {{- .Files.Get "hooks/sync.py" | nindent 4 }}