apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: daemonjobs.ops.xcloudiq.com
spec:
  group: ops.xcloudiq.com
  version: v1
  scope: Namespaced
  names:
    plural: daemonjobs
    singular: daemonjob
    kind: DaemonJob
    shortNames: 
    - dj
    - djob
  subresources:
    status: {}