apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "daemonjob-controller.fullname" . }}
  labels:
{{ include "daemonjob-controller.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "daemonjob-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "daemonjob-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        kind: daemonjob-controller
        app: {{ include "daemonjob-controller.name" . }}
    spec:
      {{ if .Values.enableSecurity }}
      securityContext:
        {{ toYaml .Values.securityContext | nindent 8 }}
      {{ end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "daemonjob-controller.image" . }} 
        imagePullPolicy: {{ include "daemonjob-controller.imagePullPolicy" . }}
        command: ["python", "/hooks/sync.py"]
        ports:
        {{- with .Values.service.ports }}
          {{- range $port, $conf := . }}
          - containerPort: {{ $conf.targetPort }}
            name: {{ $conf.name }}
          {{- end }}
        {{- end }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}   
        {{- end }}
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: hooks
        configMap:
          name: daemonjob-controller
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
