apiVersion: v1
kind: Service
metadata:
  name: {{ include "daemonjob-controller.fullname" . }}
  labels:
{{ include "daemonjob-controller.labels" . | indent 4 }}
  {{- with .Values.annotations }}
  annotations: 
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: {{ include "daemonjob-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
